#!/bin/bash

# Function to delete plugin files
delete_plugins() {
    local plugin=$1
    local directories=(
        "/Library/Audio/Plug-Ins/Components"
        "/Library/Audio/Plug-Ins/VST"
        "/Library/Audio/Plug-Ins/VST3"
        "/Library/Application Support/Avid/Audio/Plug-Ins"
    )
    local extensions=(
        "aaxplugin"
        "component"
        "vst"
        "vst3"
    )

    for directory in "${directories[@]}"; do
        for ext in "${extensions[@]}"; do
            find "$directory" -type d -name "$plugin.$ext" -exec rm -rf {} \; -print 2>/dev/null
            find "$directory" -type d -name "$plugin(m).$ext" -exec rm -rf {} \; -print 2>/dev/null
        done
    done
}

# Function to delete documentation files
delete_documentation() {
    local documentation_dir="/Applications/Universal Audio/Documentation"
    local manuals=(
#        "ADA Flanger Manual.pdf"
#        "ADA STD-1 Stereo Tapped Delay Manual.pdf"
#        "Ampeg B15N Manual.pdf"
#        "Ampeg SVT3Pro Manual.pdf"
#        "Ampeg SVTVR Classic Manual.pdf"
#        "Ampeg SVTVR Manual.pdf"
#        "AMS DMX 15-80 S Manual.pdf"
#        "AMS Neve DFC Channel Strip Manual.pdf"
#        "AMS RMX16 Expanded Manual.pdf"
#        "AMS RMX16 Manual.pdf"
#        "Antares Auto-Tune Realtime Manual.pdf"
#        "Auto-Tune Realtime Access Manual.pdf"
#        "Auto-Tune Realtime Advanced Manual.pdf"
#        "Auto-Tune Realtime X Manual.pdf"
#        "bx_digital V2 Manual.pdf"
#        "bx_digital V2 Mono Manual.pdf"
#        "bx_digital V3 Manual.pdf"
#        "bx_digital V3 mix Manual.pdf"
#        "bx_masterdesk Classic Manual.pdf"
#        "bx_masterdesk Manual.pdf"
#        "bx_refinement Manual.pdf"
#        "bx_saturator V2 Manual.pdf"
#        "bx_subsynth Manual.pdf"
#        "bx_tuner Manual.pdf"
#        "C-Suite C-Axe Manual.pdf"
#        "C-Suite C-Max Manual.pdf"
#        "C-Suite C-Vox Manual.pdf"
#        "Chandler GAV19T Manual.pdf"
#        "Chandler Limited Curve Bender Manual.pdf"
#        "Chandler Limited Zener Limiter Manual.pdf"
#        "Dangerous BAX EQ Master Manual.pdf"
#        "Dangerous BAX EQ Mix Manual.pdf"
#        "Diezel Herbert Manual.pdf"
#        "Diezel VH4 Manual.pdf"
#        "Dytronics Cyclosonic Panner Manual.pdf"
#        "Dytronics Tri-Stereo Chorus Manual.pdf"
#        "Eden WT800 Manual.pdf"
#        "elysia alpha master Manual.pdf"
#        "elysia alpha mix Manual.pdf"
#        "elysia mpressor Manual.pdf"
#        "ENGL E646 VS Manual.pdf"
#        "ENGL E765 RT Manual.pdf"
#        "ENGL Savage 120 Manual.pdf"
#        "Eventide H910 Harmonizer Manual.pdf"
#        "Friedman BE100 Manual.pdf"
#        "Friedman Buxom Betty Manual.pdf"
#        "Friedman DS40 Manual.pdf"
#        "Fuchs Overdrive Supreme 50 Manual.pdf"
#        "Fuchs Train II Manual.pdf"
#        "Gallien Krueger 800RB Manual.pdf"
#        "Maag EQ4 Manual.pdf"
#        "Marshall Bluesbreaker 1962 Manual.pdf"
#        "Marshall JMP 2203 Manual.pdf"
#        "Marshall Plexi Classic Manual.pdf"
#        "Marshall Plexi Super Lead 1959 Manual.pdf"
#        "Marshall Silver Jubilee 2555 Manual.pdf"
#        "MDWEQ5 Manual.pdf"
#        "Millennia NSEQ-2 Manual.pdf"
#        "OTO Biscuit 8-bit Effects Manual.pdf"
#        "Oxford Dynamic EQ Manual.pdf"
#        "Oxford Envolution Manual.pdf"
#        "Oxford EQ Manual.pdf"
#        "Oxford Inflator Manual.pdf"
#        "Oxford Limiter Manual.pdf"
#        "Oxford SuprEsser DS Manual.pdf"
#        "Shadow Hills Mastering Compressor Manual.pdf"
#        "Softube Amp Room Half-Stack Manual.pdf"
#        "Softube Bass Amp Room 8x10 Manual.pdf"
#        "Softube Bass Amp Room Manual.pdf"
#        "Softube Metal Amp Room Manual.pdf"
#        "Softube Vintage Amp Room Manual.pdf"
#        "Softube Vocoder Manual.pdf"
#        "Sound Machine Wood Works Manual.pdf"
#        "SPL TwinTube Manual.pdf"
#        "SPL Vitalizer MK2-T Manual.pdf"
#        "Suhr PT100 Manual.pdf"
#        "Suhr SE100 Manual.pdf"
#        "Summit Audio TLA-100A Manual.pdf"
#        "Tonelux Tilt Live Manual.pdf"
#        "Tonelux Tilt Manual.pdf"
#        "Tube-Tech CL 1B Manual.pdf"
#        "Tube-Tech CL 1B mk II Manual.pdf"
#        "Tube-Tech ME 1B Manual.pdf"
#        "Tube-Tech PE 1C Manual.pdf"
#        "UAD Plug-Ins Manual.pdf"
#        "Valley People Dyna-mite Manual.pdf"
#        "Vertigo VSC-2 Manual.pdf"
#        "Vertigo VSM-3 Manual.pdf"
    )

    for manual in "${manuals[@]}"; do
        find "$documentation_dir" -type f -name "$manual" -exec rm -rf {} \; -print 2>/dev/null
    done
}

# Function to delete the uninstaller app
delete_uninstaller() {
    local uninstaller="/Applications/Universal Audio/Uninstall Universal Audio Software.app"
    if [[ -e $uninstaller ]]; then
        echo "Deleting uninstaller: $uninstaller"
        rm -rf "$uninstaller"
    else
        echo "Uninstaller does not exist: $uninstaller"
    fi
}

# List of plugins to delete
plugins=(
#    "Console Recall"
#    "UAD 4K Buss Compressor"
#    "UAD 4K Channel Strip"
#    "UAD ADA Flanger"
#    "UAD ADA STD-1 Stereo Tapped Delay"
#    "UAD AKG BX 20"
#    "UAD Ampeg B15N"
#    "UAD Ampeg SVT3Pro"
#    "UAD Ampeg SVTVR Classic"
#    "UAD Ampeg SVTVR"
#    "UAD Ampex ATR-102"
#    "UAD AMS DMX 15-80 S"
#    "UAD AMS Neve DFC Channel Strip"
#    "UAD AMS RMX16 Expanded"
#    "UAD AMS RMX16"
#    "UAD Antares Auto-Tune Realtime"
#    "UAD API 550A"
#    "UAD API 560"
#    "UAD API 2500"
#    "UAD API Preamp"
#    "UAD API Vision Channel Strip Legacy"
#    "UAD API Vision Channel Strip"
#    "UAD Auto-Tune Realtime Access"
#    "UAD Auto-Tune Realtime Advanced"
#    "UAD Auto-Tune Realtime X"
#    "UAD Avalon VT-737sp"
#    "UAD Bermuda Triangle"
#    "UAD Brigade Chorus"
#    "UAD bx_digital V2 Mono"
#    "UAD bx_digital V2"
#    "UAD bx_digital V3 mix"
#    "UAD bx_digital V3"
#    "UAD bx_masterdesk Classic"
#    "UAD bx_masterdesk"
#    "UAD bx_refinement"
#    "UAD bx_saturator V2"
#    "UAD bx_subsynth"
#    "UAD bx_tuner"
#    "UAD C-Suite C-Axe"
#    "UAD C-Suite C-Max"
#    "UAD C-Suite C-Vox"
#    "UAD Cambridge"
#    "UAD Capitol Chambers"
#    "UAD Century Tube Channel Strip"
#    "UAD Chandler GAV19T"
#    "UAD Chandler Limited Curve Bender"
#    "UAD Chandler Limited Zener Limiter"
#    "UAD Cooper Time Cube"
#    "UAD CS-1"
#    "UAD Dangerous BAX EQ Master"
#    "UAD Dangerous BAX EQ Mix"
#    "UAD dbx 160"
#    "UAD Diezel Herbert"
#    "UAD Diezel VH4"
#    "UAD DreamVerb"
#    "UAD Dytronics Cyclosonic Panner"
#    "UAD Dytronics Tri-Stereo Chorus"
#    "UAD Eden WT800"
#    "UAD elysia alpha master"
#    "UAD elysia alpha mix"
#    "UAD elysia mpressor"
#    "UAD Empirical Labs Distressor"
#    "UAD Empirical Labs FATSO Jr"
#    "UAD Empirical Labs FATSO Sr"
#    "UAD EMT 140"
#    "UAD EMT 250"
#    "UAD ENGL E646 VS"
#    "UAD ENGL E765 RT"
#    "UAD ENGL Savage 120"
#    "UAD EP-34 Tape Echo"
#    "UAD Eventide H910 Harmonizer"
#    "UAD Fairchild 660"
#    "UAD Fairchild 670 Legacy"
#    "UAD Fairchild 670"
#    "UAD Fender 55 Tweed Deluxe"
#    "UAD Friedman BE100"
#    "UAD Friedman Buxom Betty"
#    "UAD Friedman DS40"
#    "UAD Fuchs Overdrive Supreme 50"
#    "UAD Fuchs Train II"
#    "UAD Galaxy Tape Echo"
#    "UAD Gallien Krueger 800RB"
#    "UAD Harrison 32C SE"
#    "UAD Harrison 32C"
#    "UAD Helios Type 69 Legacy"
#    "UAD Helios Type 69"
#    "UAD Hemisphere Mic Collection"
#    "UAD Hitsville EQ Mastering"
#    "UAD Hitsville EQ"
#    "UAD Hitsville Reverb Chambers"
#    "UAD Ibanez Tube Screamer TS808"
#    "UAD Korg SDD-3000"
#    "UAD LA-6176 Channel Strip"
#    "UAD Lexicon 224"
#    "UAD Lexicon 480L"
#    "UAD Little Labs IBP"
#    "UAD Little Labs VOG"
#    "UAD Maag EQ4"
#    "UAD Manley Massive Passive MST"
#    "UAD Manley Massive Passive"
#    "UAD Manley Reference Mic Preamp"
#    "UAD Manley Variable Mu"
#    "UAD Manley VOXBOX"
#    "UAD Marshall Bluesbreaker 1962"
#    "UAD Marshall JMP 2203"
#    "UAD Marshall Plexi Classic"
#    "UAD Marshall Plexi Super Lead 1959"
#    "UAD Marshall Silver Jubilee 2555"
#    "UAD MDWEQ5-3B"
#    "UAD MDWEQ5-5B"
#    "UAD Millennia NSEQ-2"
#    "UAD Moog Multimode Filter SE"
#    "UAD Moog Multimode Filter XL"
#    "UAD Moog Multimode Filter"
#    "UAD MXR Flanger-Doubler"
#    "UAD Neve 88RS Legacy"
#    "UAD Neve 88RS"
#    "UAD Neve 1073 Legacy"
#    "UAD Neve 1073"
#    "UAD Neve 1073SE Legacy"
#    "UAD Neve 1081"
#    "UAD Neve 1081SE"
#    "UAD Neve 1084"
#    "UAD Neve 2254 E Dual"
#    "UAD Neve 2254 E"
#    "UAD Neve 31102"
#    "UAD Neve 31102SE"
#    "UAD Neve 33609 C"
#    "UAD Neve 33609SE"
#    "UAD Neve Preamp"
#    "UAD Ocean Way Mic Collection 180"
#    "UAD Ocean Way Mic Collection"
#    "UAD Ocean Way Studios"
#    "UAD OTO Biscuit 8-bit Effects"
#    "UAD Oxford Dynamic EQ"
#    "UAD Oxford Envolution"
#    "UAD Oxford EQ"
#    "UAD Oxford Inflator"
#    "UAD Oxford Limiter"
#    "UAD Oxford SuprEsser DS"
#    "UAD Oxide Tape"
#    "UAD Precision Buss Compressor"
#    "UAD Precision Channel Strip"
#    "UAD Precision De-Esser"
#    "UAD Precision Delay Mod L"
#    "UAD Precision Delay Mod"
#    "UAD Precision Enhancer Hz"
#    "UAD Precision Enhancer kHz"
#    "UAD Precision Equalizer"
#    "UAD Precision K-Stereo"
#    "UAD Precision Limiter"
#    "UAD Precision Maximizer"
#    "UAD Precision Multiband"
#    "UAD Precision Reflection Engine"
#    "UAD Pultec EQP-1A Legacy"
#    "UAD Pultec EQP-1A"
#    "UAD Pultec HLF-3C"
#    "UAD Pultec MEQ-5"
#    "UAD Pultec-Pro Legacy"
#    "UAD Pure Plate"
#    "UAD Putnam Mic Collection 180"
#    "UAD Putnam Mic Collection"
#    "UAD Raw"
#    "UAD RealVerb-Pro"
#    "UAD Roland CE-1"
#    "UAD Roland Dimension D"
#    "UAD Roland RE-201"
#    "UAD Shadow Hills Mastering Compressor"
#    "UAD Softube Amp Room Half-Stack"
#    "UAD Softube Bass Amp Room 8x10"
#    "UAD Softube Bass Amp Room"
#    "UAD Softube Metal Amp Room"
#    "UAD Softube Vintage Amp Room"
#    "UAD Softube Vocoder"
#    "UAD Sound Machine Wood Works"
#    "UAD Sphere Mic Collection 180"
#    "UAD Sphere Mic Collection"
#    "UAD SPL Transient Designer"
#    "UAD SPL TwinTube"
#    "UAD SPL Vitalizer MK2-T"
#    "UAD SSL E Channel Strip Legacy"
#    "UAD SSL E Channel Strip"
#    "UAD SSL G Bus Compressor Legacy"
#    "UAD SSL G Bus Compressor"
#    "UAD Studer A800"
#    "UAD Studio D Chorus"
#    "UAD Suhr PT100"
#    "UAD Suhr SE100"
#    "UAD Summit Audio TLA-100A"
#    "UAD Teletronix LA-2"
#    "UAD Teletronix LA-2A Gray"
#    "UAD Teletronix LA-2A Legacy"
#    "UAD Teletronix LA-2A Silver"
#    "UAD Teletronix LA-3A"
#    "UAD Thermionic Culture Vulture"
#    "UAD Tonelux Tilt Live"
#    "UAD Tonelux Tilt"
#    "UAD Trident A-Range"
#    "UAD TS Overdrive"
#    "UAD Tube-Tech CL 1B mk II"
#    "UAD Tube-Tech CL 1B"
#    "UAD Tube-Tech ME 1B"
#    "UAD Tube-Tech PE 1C"
#    "UAD UA 175-B"
#    "UAD UA 176"
#    "UAD UA 610-A"
#    "UAD UA 610-B"
#    "UAD UA 1176 Rev A"
#    "UAD UA 1176AE"
#    "UAD UA 1176LN Legacy"
#    "UAD UA 1176LN Rev E"
#    "UAD UA 1176SE Legacy"
#    "UAD V76 Preamp"
#    "UAD Valley People Dyna-mite"
#    "UAD Vertigo VSC-2"
#    "UAD Vertigo VSM-3"
)

# Loop through plugins and delete them
for plugin in "${plugins[@]}"; do
    delete_plugins "$plugin"
    delete_documentation "$plugin"
done

# Delete the uninstaller
delete_uninstaller

echo "Cleanup complete!"
